# Generated by Django 3.1.7 on 2021-03-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('bitsapp', '0003_auto_20210315_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact_Email', models.EmailField(max_length=254)),
                ('dp', models.ImageField(default='default.png', upload_to='profilepics')),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='socialaccount.socialaccount')),
            ],
        ),
    ]
